@app.route('/exception')
def exception(request):
    raise ServerError('yep')

----------

def test_warn_on_duplicate(app: Sanic, caplog: LogCaptureFixture, recwarn: WarningsRecorder):

    @app.exception(ServerError)
    async def exception_handler_1(request, exception):
        ...

    @app.exception(ServerError)
    async def exception_handler_2(request, exception):
        ...
    assert len(caplog.records) == 1
    assert len(recwarn) == 1
    assert caplog.records[0].message == "Duplicate exception handler definition on: route=__ALL_ROUTES__ and exception=<class 'sanic.exceptions.ServerError'>"

----------



Test Class Name: ModuleNotFoundError